### ISSUE TITLE
Problem in tailwind.config.js

### ISSUE THREAD

**Issue by Debajyoti045** [Rishavagarwal12345/Hacktoberfest-2023#47] opened 2023-09-30 20:24 UTC
problem in tailwind.config.js file

**Comment by Haris-Mohanty** [comment] 2023-09-30 20:25
Hi @Debajyoti045 bro, what's the problem is?

**Comment by Shubham-kumar-iem** [comment] 2023-10-01 05:16
hello..

**Comment by Ashima2003** [comment] 2023-10-01 06:00
I can fix this issue can you assign this task to me

**Comment by parthivghose2919** [comment] 2023-10-01 06:02
Hii@Debajyoti045 bhaiya,Can you please a detailed insight about what exactly the problem you are  facing...if so i can fix this issue can you assign this task to me??

**Comment by aditya-0786** [comment] 2023-10-01 08:08
Hello Rishav bhaiya. I am 1st year student of b.tech from tier 3 college. So this competition is very important for my future.So please can you assign this project to me. It would be great help for me🙏🙏

**Comment by kartik9977** [comment] 2023-10-01 08:24
Hello sir, Can you please assign me this project. It is very helpful for me.

**Closed** 2023-10-01 08:55 UTC
Labels: hacktoberfest, hacktoberfest-accepted
